2021-12-18 01:30:53,194 (7f116f8c9848) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: c43dc02 (Wed Dec 08 14:16:51 UTC 2021)
2021-12-18 01:30:53,195 (7f116f8c9848) :  DEBUG (core:361) - Using the elevated policy
2021-12-18 01:30:53,195 (7f116f8c9848) :  DEBUG (core:365) - Extending whitelist: ['cgi', 'tempfile']
2021-12-18 01:30:53,196 (7f116f8c9848) :  DEBUG (core:450) - Starting runtime component.
2021-12-18 01:30:53,198 (7f116f8c9848) :  DEBUG (core:450) - Starting caching component.
2021-12-18 01:30:53,199 (7f116f8c9848) :  DEBUG (core:450) - Starting data component.
2021-12-18 01:30:53,204 (7f116f8c9848) :  DEBUG (core:450) - Starting networking component.
2021-12-18 01:30:53,207 (7f116f8c9848) :  DEBUG (networking:261) - Loaded HTTP cookies
2021-12-18 01:30:53,213 (7f116f8c9848) :  DEBUG (caching:108) - No info file found, trashing the cache folder
2021-12-18 01:30:53,460 (7f116f8c9848) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2021-12-18 01:30:53,461 (7f116f8c9848) :  DEBUG (core:450) - Starting localization component.
2021-12-18 01:30:53,461 (7f116f8c9848) :  INFO (localization:409) - Setting the default locale to en-us
2021-12-18 01:30:53,462 (7f116f8c9848) :  WARNING (data:179) - Error decoding with simplejson, using demjson instead (this will cause a performance hit) - Expecting property name enclosed in double quotes: line 26 column 1 (char 1078)
2021-12-18 01:30:53,464 (7f116f8c9848) :  DEBUG (localization:427) - Loaded en strings
2021-12-18 01:30:53,464 (7f116f8c9848) :  DEBUG (core:450) - Starting messaging component.
2021-12-18 01:30:53,465 (7f116f8c9848) :  DEBUG (core:450) - Starting debugging component.
2021-12-18 01:30:53,465 (7f116f8c9848) :  DEBUG (core:450) - Starting services component.
2021-12-18 01:30:53,466 (7f116f8c9848) :  DEBUG (core:450) - Starting myplex component.
2021-12-18 01:30:53,466 (7f116f8c9848) :  DEBUG (core:450) - Starting notifications component.
2021-12-18 01:30:53,663 (7f116f8c9848) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.system in namespace 'metadata'
2021-12-18 01:30:53,676 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2021-12-18 01:30:53,676 (7f116c660b38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2021-12-18 01:30:53,678 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2021-12-18 01:30:53,680 (7f116f8c9848) :  DEBUG (core:150) - Finished starting framework core
2021-12-18 01:30:53,682 (7f116f8c9848) :  DEBUG (core:560) - Loading plug-in code
2021-12-18 01:30:53,691 (7f116c61ab38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2021-12-18 01:30:53,691 (7f116c660b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2021-12-18 01:30:53,726 (7f116f8c9848) :  DEBUG (core:566) - Finished loading plug-in code
2021-12-18 01:30:53,726 (7f116f8c9848) :  DEBUG (runtime:640) - Adding a prefix handler for 'System' ('/system')
2021-12-18 01:30:54,475 (7f116f8c9848) :  INFO (__init__:35) - Starting System c43dc02 (Wed Dec 08 14:16:51 UTC 2021)
2021-12-18 01:30:54,475 (7f116f8c9848) :  DEBUG (runtime:640) - Adding a prefix handler for 'Player' ('/player')
2021-12-18 01:30:54,481 (7f116f8c9848) :  INFO (datakit:93) - Loaded the dictionary file
2021-12-18 01:30:54,482 (7f116f8c9848) :  DEBUG (agentservice:52) - Starting the agent service
2021-12-18 01:30:54,624 (7f116f8c9848) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.system in namespace 'metadata'
2021-12-18 01:30:54,632 (7f116f8c9848) :  DEBUG (bundleservice:65) - Starting the bundle service
2021-12-18 01:30:54,634 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'start'
2021-12-18 01:30:54,635 (7f116f8c9848) :  DEBUG (playerservice:12) - Starting the player service
2021-12-18 01:30:54,637 (7f116f8c9848) :  DEBUG (flagservice:13) - Starting the media flag service
2021-12-18 01:30:54,638 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'start'
2021-12-18 01:30:54,639 (7f116f8c9848) :  DEBUG (peerservice:141) - Starting the peer service
2021-12-18 01:30:54,642 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,643 (7f116c3e4b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.themoviedb not in info dictionary - pinging!
2021-12-18 01:30:54,645 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'refresh_servers'
2021-12-18 01:30:54,646 (7f116c3c1b38) :  DEBUG (peerservice:164) - Fetching the current list of servers
2021-12-18 01:30:54,648 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,650 (7f116f8c9848) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'refresh_servers'
2021-12-18 01:30:54,652 (7f116f8c9848) :  DEBUG (streamservice:18) - Starting the stream service
2021-12-18 01:30:54,654 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,655 (7f116f8c9848) :  CRITICAL (runtime:709) - Private handlers are no longer supported; couldn't register <bound method StreamService.token_handler of <streamservice.StreamService object at 0x7f116bfe6b90>>
2021-12-18 01:30:54,657 (7f116f8c9848) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'invalidation_timer'
2021-12-18 01:30:54,661 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,662 (7f116c3e4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.themoviedb'
2021-12-18 01:30:54,661 (7f116c3c1b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/servers'
2021-12-18 01:30:54,662 (7f116f8c9848) :  DEBUG (proxyservice:12) - Starting the proxy service
2021-12-18 01:30:54,668 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,674 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'update_attribution_flags_inner'
2021-12-18 01:30:54,675 (7f116f8c9848) :  INFO (core:611) - Started plug-in
2021-12-18 01:30:54,676 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,676 (7f116f8c9848) :  DEBUG (socketinterface:160) - Starting socket server
2021-12-18 01:30:54,679 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,680 (7f116f8c9848) :  DEBUG (runtime:1117) - Created a thread named 'start'
2021-12-18 01:30:54,681 (7f116f8c9848) :  INFO (socketinterface:184) - Socket server started on port 39353
2021-12-18 01:30:54,682 (7f116f8c9848) :  INFO (pipeinterface:25) - Entering run loop
2021-12-18 01:30:54,683 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,683 (7f116f8c9848) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2021-12-18 01:30:54,689 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,691 (7f116f8c9848) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2021-12-18 01:30:54,693 (7f116c42ab38) :  CRITICAL (storage:60) - Exception reading file /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 55, in load
    f = open(filename, mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist'

2021-12-18 01:30:54,695 (7f116f8c9848) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 486 bytes
2021-12-18 01:30:54,696 (7f116c42ab38) :  CRITICAL (bundleservice:141) - Exception adding bundle: WebClient.bundle (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 131, in update_bundles
    Log('Found duplicate identifier at %s for bundled plugin (%s), ignoring duplicate plugin.' % (path, bundle.identifier))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 18, in __init__
    self.load_plist()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 22, in load_plist
    plist = Plist.ObjectFromString(Core.storage.load(Core.storage.join_path(self.path, "Contents", "Info.plist")))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 32, in ObjectFromString
    check_size(string, max_size)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 22, in check_size
    if len(data) > max_size:
TypeError: object of type 'NoneType' has no len()

2021-12-18 01:30:54,699 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,702 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,706 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,707 (7f116b863b38) :  DEBUG (runtime:717) - Handling request GET /system/agents
2021-12-18 01:30:54,709 (7f116c42ab38) :  INFO (bundleservice:131) - Found duplicate identifier at /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/TheTVDBv4.bundle for bundled plugin (com.plexapp.agents.thetvdb), ignoring duplicate plugin.
2021-12-18 01:30:54,719 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,725 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,751 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,765 (7f116b863b38) :  DEBUG (runtime:814) - Found route matching /system/agents
2021-12-18 01:30:54,765 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,770 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,772 (7f116c42ab38) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2021-12-18 01:30:54,772 (7f116c42ab38) :  DEBUG (bundleservice:81) - Started the bundle service
2021-12-18 01:30:54,776 (7f116b99eb38) :  INFO (agentservice:129) - Agent info: {'com.plexapp.agents.movieposterdb': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'CineMaterial'}]}
2021-12-18 01:30:54,779 (7f116c3e4b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.themoviedb'
2021-12-18 01:30:54,797 (7f116c3e4b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,794 (7f116c3c1b38) :  DEBUG (peerservice:171) - Refreshing local server
2021-12-18 01:30:54,789 (7f116b76eb38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:54,787 (7f116c407b38) :  DEBUG (flagservice:46) - Started the media flag service
2021-12-18 01:30:54,800 (7f116c61ab38) :  DEBUG (core:538) - Machine identifier is 60630771a5d0018f3381e1622e019e58a1c14b9f
2021-12-18 01:30:54,801 (7f116c39eb38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.localmedia not in info dictionary - pinging!
2021-12-18 01:30:54,802 (7f116c3c1b38) :  DEBUG (peerservice:189) - Updating servers (True/False True/True/True)
2021-12-18 01:30:54,803 (7f116b863b38) :  CRITICAL (storage:60) - Exception reading file /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 55, in load
    f = open(filename, mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist'

2021-12-18 01:30:54,813 (7f116b99eb38) :  INFO (datakit:131) - Saved the dictionary file
2021-12-18 01:30:54,815 (7f116c61ab38) :  DEBUG (core:539) - Server version is 1.25.2.5319-c43dc0277
2021-12-18 01:30:54,824 (7f116c3c1b38) :  DEBUG (peerservice:198) - Found 1 servers
2021-12-18 01:30:54,827 (7f116b863b38) :  CRITICAL (bundleservice:141) - Exception adding bundle: WebClient.bundle (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 131, in update_bundles
    Log('Found duplicate identifier at %s for bundled plugin (%s), ignoring duplicate plugin.' % (path, bundle.identifier))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 18, in __init__
    self.load_plist()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 22, in load_plist
    plist = Plist.ObjectFromString(Core.storage.load(Core.storage.join_path(self.path, "Contents", "Info.plist")))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 32, in ObjectFromString
    check_size(string, max_size)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 22, in check_size
    if len(data) > max_size:
TypeError: object of type 'NoneType' has no len()

2021-12-18 01:30:54,832 (7f116c3c1b38) :  DEBUG (peerservice:230) - Creating new server docker-desktop (60630771a5d0018f3381e1622e019e58a1c14b9f)
2021-12-18 01:30:54,838 (7f116c39eb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.localmedia'
2021-12-18 01:30:54,841 (7f116b863b38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,851 (7f116c39eb38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.localmedia'
2021-12-18 01:30:54,854 (7f116c39eb38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,856 (7f116c3c1b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/sections'
2021-12-18 01:30:54,860 (7f116b9e4b38) :  INFO (agentservice:167) - Agents in tv.plex.agents.music not in info dictionary - pinging!
2021-12-18 01:30:54,862 (7f116b791b38) :  CRITICAL (storage:60) - Exception reading file /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 55, in load
    f = open(filename, mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist'

2021-12-18 01:30:54,869 (7f116b791b38) :  CRITICAL (bundleservice:141) - Exception adding bundle: WebClient.bundle (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 131, in update_bundles
    Log('Found duplicate identifier at %s for bundled plugin (%s), ignoring duplicate plugin.' % (path, bundle.identifier))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 18, in __init__
    self.load_plist()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 22, in load_plist
    plist = Plist.ObjectFromString(Core.storage.load(Core.storage.join_path(self.path, "Contents", "Info.plist")))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 32, in ObjectFromString
    check_size(string, max_size)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 22, in check_size
    if len(data) > max_size:
TypeError: object of type 'NoneType' has no len()

2021-12-18 01:30:54,874 (7f116b791b38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:54,884 (7f116b9e4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.music'
2021-12-18 01:30:54,892 (7f116b76eb38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:54,896 (7f116b76eb38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:54,897 (7f116b76eb38) :  DEBUG (runtime:924) - Response: [200] str, 516 bytes
2021-12-18 01:30:54,898 (7f116b9e4b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.music'
2021-12-18 01:30:54,900 (7f116c3c1b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/channels/all'
2021-12-18 01:30:54,901 (7f116b9e4b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,904 (7f116b9c1b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.fanarttv not in info dictionary - pinging!
2021-12-18 01:30:54,909 (7f116c660b38) :  DEBUG (services:362) - Loaded services
2021-12-18 01:30:54,918 (7f116c63db38) :  DEBUG (services:438) - No shared code to load
2021-12-18 01:30:54,921 (7f116c660b38) :  DEBUG (peerservice:176) - Background-refreshing remote servers
2021-12-18 01:30:54,922 (7f116c660b38) :  DEBUG (peerservice:189) - Updating servers (True/False True/True/True)
2021-12-18 01:30:54,923 (7f116c3c1b38) :  DEBUG (runtime:1117) - Created a thread named 'background_refresh'
2021-12-18 01:30:54,923 (7f116c660b38) :  DEBUG (peerservice:198) - Found 1 servers
2021-12-18 01:30:54,925 (7f116c660b38) :  DEBUG (peerservice:233) - Updating existing server docker-desktop (60630771a5d0018f3381e1622e019e58a1c14b9f)
2021-12-18 01:30:54,926 (7f116b9c1b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.fanarttv'
2021-12-18 01:30:54,932 (7f116b9c1b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.fanarttv'
2021-12-18 01:30:54,933 (7f116b9c1b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,934 (7f116b97bb38) :  INFO (agentservice:167) - Agents in org.musicbrainz.agents.music not in info dictionary - pinging!
2021-12-18 01:30:54,936 (7f116c660b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/sections'
2021-12-18 01:30:54,948 (7f116b97bb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/org.musicbrainz.agents.music'
2021-12-18 01:30:54,952 (7f116b97bb38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/org.musicbrainz.agents.music'
2021-12-18 01:30:54,953 (7f116b97bb38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,954 (7f116b958b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.opensubtitles not in info dictionary - pinging!
2021-12-18 01:30:54,957 (7f116c660b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/channels/all'
2021-12-18 01:30:54,968 (7f116b958b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.opensubtitles'
2021-12-18 01:30:54,971 (7f116b958b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.opensubtitles'
2021-12-18 01:30:54,972 (7f116b958b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,972 (7f116b912b38) :  INFO (agentservice:167) - Agents in tv.plex.agents.series not in info dictionary - pinging!
2021-12-18 01:30:54,986 (7f116b912b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.series'
2021-12-18 01:30:54,989 (7f116b912b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.series'
2021-12-18 01:30:54,990 (7f116b912b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:54,990 (7f116b8efb38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.imdb not in info dictionary - pinging!
2021-12-18 01:30:55,006 (7f116b8efb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.imdb'
2021-12-18 01:30:55,011 (7f116b8efb38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.imdb'
2021-12-18 01:30:55,011 (7f116b8efb38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,012 (7f116b8ccb38) :  INFO (agentservice:167) - Agents in tv.plex.agents.movie not in info dictionary - pinging!
2021-12-18 01:30:55,027 (7f116b8ccb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.movie'
2021-12-18 01:30:55,031 (7f116b8ccb38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/tv.plex.agents.movie'
2021-12-18 01:30:55,032 (7f116b8ccb38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,033 (7f116b8a9b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.thetvdb not in info dictionary - pinging!
2021-12-18 01:30:55,051 (7f116b8a9b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,055 (7f116b8a9b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,055 (7f116b8a9b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,056 (7f116b886b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.thetvdb not in info dictionary - pinging!
2021-12-18 01:30:55,067 (7f116b886b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,070 (7f116b886b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,071 (7f116b886b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,071 (7f116b840b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.lastfm not in info dictionary - pinging!
2021-12-18 01:30:55,084 (7f116b840b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.lastfm'
2021-12-18 01:30:55,087 (7f116b840b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.lastfm'
2021-12-18 01:30:55,087 (7f116b840b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,088 (7f116b81db38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.plexthememusic not in info dictionary - pinging!
2021-12-18 01:30:55,099 (7f116b81db38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.plexthememusic'
2021-12-18 01:30:55,101 (7f116b81db38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.plexthememusic'
2021-12-18 01:30:55,102 (7f116b81db38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,102 (7f116b7fab38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.lyricfind not in info dictionary - pinging!
2021-12-18 01:30:55,115 (7f116b7fab38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.lyricfind'
2021-12-18 01:30:55,118 (7f116b7fab38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.lyricfind'
2021-12-18 01:30:55,118 (7f116b7fab38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,119 (7f116b7d7b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.htbackdrops not in info dictionary - pinging!
2021-12-18 01:30:55,131 (7f116b7d7b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.htbackdrops'
2021-12-18 01:30:55,134 (7f116b7d7b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.htbackdrops'
2021-12-18 01:30:55,134 (7f116b7d7b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,135 (7f116b7b4b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.none not in info dictionary - pinging!
2021-12-18 01:30:55,148 (7f116b7b4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.none'
2021-12-18 01:30:55,151 (7f116b7b4b38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.none'
2021-12-18 01:30:55,151 (7f116b7b4b38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,152 (7f116c61ab38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.thetvdb not in info dictionary - pinging!
2021-12-18 01:30:55,166 (7f116c61ab38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,170 (7f116c61ab38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,171 (7f116c61ab38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,172 (7f116c41ab38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.thetvdb not in info dictionary - pinging!
2021-12-18 01:30:55,182 (7f116c41ab38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,185 (7f116c41ab38) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:55,185 (7f116c41ab38) :  WARNING (agentservice:169) - We weren't able to get information from the server about the agents.
2021-12-18 01:30:55,187 (7f116b863b38) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 248 bytes
2021-12-18 01:30:56,504 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.plexthememusic
2021-12-18 01:30:56,561 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.plexthememusic
2021-12-18 01:30:56,562 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:56,563 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2021-12-18 01:30:56,744 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.thetvdb
2021-12-18 01:30:56,745 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.thetvdb
2021-12-18 01:30:56,747 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:56,748 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2021-12-18 01:30:56,838 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:56,840 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:56,858 (7f116c41ab38) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.imdb
2021-12-18 01:30:56,866 (7f116c41ab38) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.imdb
2021-12-18 01:30:56,868 (7f116c41ab38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:56,871 (7f116c41ab38) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2021-12-18 01:30:56,872 (7f116c63db38) :  DEBUG (networking:143) - Requesting 'http://resources-cdn.plexapp.com/hashes.json'
2021-12-18 01:30:56,983 (7f116c41ab38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:56,986 (7f116c41ab38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:57,021 (7f116c3e3b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:57,023 (7f116c3e3b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2021-12-18 01:30:57,066 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,069 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2021-12-18 01:30:57,071 (7f116c3e3b38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,073 (7f116c3e3b38) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2021-12-18 01:30:57,074 (7f116c41ab38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,078 (7f116c41ab38) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2021-12-18 01:30:57,157 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,167 (7f116c63db38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:57,170 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,173 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,174 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 516 bytes
2021-12-18 01:30:57,259 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo2CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0CjIKczMzCmNvbS5wbGV4YXBwLmFnZW50cy5wbGV4dGhlbWVtdXNpY3MxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI0CnMxNApjb250cmlidXRlc190b3I1CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIwczE2CnByaW1hcnlfcHJvdmlkZXJiMHM1CnByZWZzczE2ClBsZXggVGhlbWUgTXVzaWNzNApuYW1lMQpzNwpUVl9TaG93MwpzMjYKY29tLnBsZXhhcHAuYWdlbnRzLnRoZXR2ZGJzMzQKY29tLnBsZXhhcHAuYWdlbnRzLnRoZXR2ZGJkdmRvcmRlcnMyOQpjb20ucGxleGFwcC5hZ2VudHMudGhlbW92aWVkYjEKczIKeG5yMAo_
2021-12-18 01:30:57,261 (7f116c63db38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:57,267 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo2CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0CjIKczMzCmNvbS5wbGV4YXBwLmFnZW50cy5wbGV4dGhlbWVtdXNpY3MxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI0CnMxNApjb250cmlidXRlc190b3I1CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIwczE2CnByaW1hcnlfcHJvdmlkZXJiMHM1CnByZWZzczE2ClBsZXggVGhlbWUgTXVzaWNzNApuYW1lMQpzNwpUVl9TaG93MwpzMjYKY29tLnBsZXhhcHAuYWdlbnRzLnRoZXR2ZGJzMzQKY29tLnBsZXhhcHAuYWdlbnRzLnRoZXR2ZGJkdmRvcmRlcnMyOQpjb20ucGxleGFwcC5hZ2VudHMudGhlbW92aWVkYjEKczIKeG5yMAo_
2021-12-18 01:30:57,269 (7f116c63db38) :  INFO (agentservice:175) - Receiving agent info from com.plexapp.agents.plexthememusic: [{'media_types': ['TV_Show'], 'primary_provider': False, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb', 'com.plexapp.agents.thetvdbdvdorder', 'com.plexapp.agents.themoviedb'], 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'accepts_from': None, 'prefs': False, 'name': 'Plex Theme Music'}]
2021-12-18 01:30:57,274 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,274 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2021-12-18 01:30:57,284 (7f116c63db38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,286 (7f116c41ab38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,291 (7f116c41ab38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:57,293 (7f116c41ab38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,289 (7f116c63db38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:57,300 (7f116c63db38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2021-12-18 01:30:57,297 (7f116c41ab38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,302 (7f116c41ab38) :  DEBUG (runtime:924) - Response: [200] str, 516 bytes
2021-12-18 01:30:57,323 (7f116c63db38) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2021-12-18 01:30:57,335 (7f116c63db38) :  DEBUG (runtime:924) - Response: [200] str, 516 bytes
2021-12-18 01:30:57,340 (7f116c41ab38) :  DEBUG (runtime:717) - Handling request GET /system/agents
2021-12-18 01:30:57,347 (7f116c41ab38) :  DEBUG (runtime:814) - Found route matching /system/agents
2021-12-18 01:30:57,357 (7f116c41ab38) :  CRITICAL (storage:60) - Exception reading file /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 55, in load
    f = open(filename, mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/WebClient.bundle/Contents/Info.plist'

2021-12-18 01:30:57,360 (7f116c41ab38) :  CRITICAL (bundleservice:141) - Exception adding bundle: WebClient.bundle (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 131, in update_bundles
    Log('Found duplicate identifier at %s for bundled plugin (%s), ignoring duplicate plugin.' % (path, bundle.identifier))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 18, in __init__
    self.load_plist()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/System.bundle/Contents/Code/bundleservice.py", line 22, in load_plist
    plist = Plist.ObjectFromString(Core.storage.load(Core.storage.join_path(self.path, "Contents", "Info.plist")))
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 32, in ObjectFromString
    check_size(string, max_size)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 22, in check_size
    if len(data) > max_size:
TypeError: object of type 'NoneType' has no len()

2021-12-18 01:30:57,362 (7f116c3e3b38) :  INFO (agentservice:167) - Agents in com.plexapp.agents.thetvdb not in info dictionary - pinging!
2021-12-18 01:30:57,363 (7f116c41ab38) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2021-12-18 01:30:57,382 (7f116c3e3b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.thetvdb'
2021-12-18 01:30:57,869 (7f116c3c0b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__
2021-12-18 01:30:57,870 (7f116c3c0b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:57,872 (7f116c3c0b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__
2021-12-18 01:30:58,191 (7f116bcebb38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2021-12-18 01:30:58,193 (7f116bcebb38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-18 01:30:58,196 (7f116bcebb38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2021-12-18 01:30:59,736 (7f116b9e4b38) :  DEBUG (runtime:717) - Handling request GET /system/notify/serverUpdated?host=127.0.0.1
2021-12-18 01:30:59,744 (7f116b9e4b38) :  DEBUG (runtime:814) - Found route matching /system/notify/serverUpdated
2021-12-18 01:30:59,746 (7f116b9e4b38) :  DEBUG (peerservice:386) - Handling server update notification (127.0.0.1)
2021-12-18 01:30:59,748 (7f116b9e4b38) :  DEBUG (peerservice:189) - Updating servers (True/False True/True/True)
2021-12-18 01:30:59,750 (7f116b9e4b38) :  DEBUG (peerservice:164) - Fetching the current list of servers
2021-12-18 01:30:59,778 (7f116b9e4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/servers'
2021-12-18 01:30:59,788 (7f116b9e4b38) :  DEBUG (peerservice:198) - Found 1 servers
2021-12-18 01:30:59,789 (7f116b9e4b38) :  DEBUG (peerservice:214) - Ignoring 60630771a5d0018f3381e1622e019e58a1c14b9f because host != 127.0.0.1 (192.168.65.3)
2021-12-18 01:30:59,800 (7f116b9e4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/sections'
2021-12-18 01:30:59,822 (7f116b9e4b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/channels/all'
2021-12-18 01:30:59,828 (7f116b9e4b38) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2021-12-18 01:31:00,186 (7f116c660b38) :  INFO (datakit:131) - Saved the dictionary file
